### ISSUE TITLE
카카오플러스 10-22 안에 완료 

### ISSUE THREAD

**Issue by kimteayoun** [kimteayoun/MOIMOI#15]
1>카카오톡 플러스 친구 가입 
2>본 웹 모바일에서 바로가기 걸기 (확인 필요)
3>전체 광고 돌리기 ,,,test

**Comment by kimteayoun** [comment]
1>카카오플러스 가입 
     -카카오플러스 가입하고 1:1 채팅상당 가입알람 확인 
2>본 웹 모바일에서 바로가기 
     -모방리에서는 가능하지만 웹에서는 불가능 딸로 플러스 친구를 등록하여 "채팅하기" 해야함 

3>전체 광고 돌리기 ,,,test 
완료 '
![screenclip](https://user-images.githubusercontent.com/7638177/47409940-3a23d980-d79f-11e8-9620-fe046c1fbd2f.png)

**Comment by kimteayoun** [comment]
카카오플러스 사용설명서 드라이브에 올림

**Comment by baekminjung** [comment]
ㅎㅎ
