### ISSUE TITLE
폼클렌징11월 추가할 일정이 있으면 글달아 주세요, 혹은 이슈추가

### ISSUE THREAD

**Issue by kimteayoun** [kimteayoun/MOIMOI#26]
11월 폼클렌징(180-200ml)
-민정 아는 오빠 홈페이지에서 판매 (사전에 영상기획)
-블로그,인스타 홍보작업 사전 필요 
-디자인은 오투잡에서 디지이너서치

**Comment by baekminjung** [comment]
11월 1일 - [더마트럽] 상표권 출원 관련 견적서, 서류 수령 완료
11월 1일 - [더마트럽] 로고 디자인 관련 디자이너 선정예정 -> 디자인 작업의뢰예정
11월 2일 - 인감증명서 및 서류 발송 [특허사무소] 예정
11월 2일 - 상표출원 요청 결제 예정

**Comment by baekminjung** [comment]
> 11월 1일 - [더마트럽] 상표권 출원 관련 견적서, 서류 수령 완료
> 11월 1일 - [더마트럽] 로고 디자인 관련 디자인 작업의뢰 완료 [15만원]
   https://www.otwojob.com/product/143987858567 [디자이너]
> 11월 2일 - 인감증명서 및 서류 발송 [특허사무소] 예정
> 11월 2일 - 상표출원 요청 결제 예정
> 11월 4일 (일) 오전 - 1차 디자인 시안 수령 예정

[작업의뢰서_ 로고디자인_‘DERMA T.ROUB’ 181102.pdf](https://github.com/kimteayoun/MOIMOI/files/2541011/_._.DERMA.T.ROUB.181102.pdf)
